# Site settings
title: SUNY Morrisville Developer Blog
email: web@morrisville.edu
description: "Morrisville State College Web Developer Blog"
baseurl: ""
url: "http://mscweb.github.io"
twitter_username: 
github_username:  mscweb

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
highlighter: pygments
